Backend e serviços na nuvem da Microsoft Azure/aula04/EJOGOS/Models/Equipe.cs
using EJOGOS.Interface;
using System.Collections.Generic;
using System.IO;

namespace EJOGOS.Models
{

    //: Herança
    //, Interface (contrato da classe)

    public class Equipe : EquipeBase, IEquipe
    {
        public int idEquipe { get; set; }
        public string Nome { get; set; }
        public string Imagem { get; set; }

        //variavel de dados.
        private const string caminhobd = "Database/equipe.csv";


        public Equipe()
        {

            //metodo da classe de herança EquipeBase.
            CriarPastaOuArquivo(caminhobd);
        }


        //criar uma funcao que vai receber o objeto EQUIPE,
        // e vai retornar no formato de csv. (STRING)

        private string Preparar(Equipe e)
        {
            //return e.idEquipe + ";" + e.Nome + ";" + e.Imagem;

            return $"{ e.idEquipe};{e.Nome};{e.Imagem}";

        }
        public void Criar(Equipe novaequipe)
        {
            string valor = Preparar(novaequipe);

            //array de strings =   na posicao 0 temos o retorno do "Preparar".
            string[] equipe_texto = { valor };

            //arquivo vamos adicionar uma nova linha.
            //caminho do arquivo,  string em formato array.
            File.AppendAllLines(caminhobd, equipe_texto);
        }

        public List<Equipe> LerEquipes()
        {
            List<Equipe> listaEquipes = new List<Equipe>();

            //ler todas as linhas do arquivo csv, armazenar em um array;
            string[] linhas = File.ReadAllLines(caminhobd);

            foreach (string item in linhas)
            {
                // 1; nome da equipe;  caminho da imagem
                string[] linhaEquipe = item.Split(';');

                Equipe equipeAtual = new Equipe();
                equipeAtual.idEquipe = int.Parse(linhaEquipe[0]);
                equipeAtual.Nome = linhaEquipe[1];
                equipeAtual.Imagem = linhaEquipe[2];

                listaEquipes.Add(equipeAtual);
            }
            return listaEquipes;

        }
    }
}

Backend e serviços na nuvem da Microsoft Azure/aula04/EJOGOS/Models/EquipeBase.cs
using System.IO;

namespace EJOGOS.Models
{
    public class EquipeBase
    {
        public void CriarPastaOuArquivo(string caminho)
        {
            // "nome da pasta/nomedoarquivo.csv"
            string pasta = caminho.Split('/')[0];

            //se o diretorio nao existir, criar a pasta.
            if(!Directory.Exists(pasta))
            {
                Directory.CreateDirectory(pasta);
            }

            if (!File.Exists(caminho))
            {
                File.Create(caminho);
            }
        }
    }
}

Backend e serviços na nuvem da Microsoft Azure/aula04/EJOGOS/Models/ErrorViewModel.cs
using System;

namespace EJOGOS.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Backend e serviços na nuvem da Microsoft Azure/aula04/EJOGOS/Controllers/EquipeController.cs
using EJOGOS.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace EJOGOS.Controllers
{
    public class EquipeController : Controller
    {

        //ActionResult representam os varios codigos HTTP,

        //Codigos HTTP - https://developer.mozilla.org/pt-BR/docs/Web/HTTP/Status


        Equipe equipeModel = new Equipe();

        public IActionResult Index()
        {
            //ViewBag = Reserva de espaco para armazenar informacoes para recuparar na VIEW.

            //ViewBag = tem a função de "carregar" as informaçoes do Controller para a 
             // VIEW.

            ViewBag.Equipes = equipeModel.LerEquipes();

            return View();
        }

        public IActionResult Cadastrar(IFormCollection form)
        {
            //criar uma objeto equipe a partir do frontend. 
            // IFormCollection

            Equipe novaEquipe = new Equipe();

            novaEquipe.idEquipe = int.Parse(form["IdEquipe"]);
            novaEquipe.Nome = form["Nome"];
            novaEquipe.Imagem = form["Imagem"];

            //chamar a funcao CRIAR passando um objeto do tipo EQUIPE.
            equipeModel.Criar(novaEquipe);

            ViewBag.Equipes = equipeModel.LerEquipes();

            return LocalRedirect("~/Equipe");

        }



    }
}

Backend e serviços na nuvem da Microsoft Azure/aula04/EJOGOS/Controllers/HomeController.cs
using EJOGOS.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace EJOGOS.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Backend e serviços na nuvem da Microsoft Azure/aula04/EJOGOS/Views/Equipe/Index.cshtml
@model Equipe

@{
    ViewData["Title"] = "Equipes";  
}



<form method="POST" action='@Url.Action("Cadastrar")'>
    <label>ID</label>
    <input type="text" name="IdEquipe" />

    <label>Nome</label>
    <input type="text" name="Nome" />

    <label>Imagem</label>
    <input type="text" name="Imagem" />

    <button type="submit">Cadastrar</button>
</form>


//TABLE PARA MOSTRAR A LISTA

<table class="table table-striped table-responsive">
    <thead>
        <th>ID</th>
        <th>Nome</th>
        <th>Foto</th>
    </thead>
    <tbody>
        @foreach(Equipe e in ViewBag.Equipes){
            <tr>
                <td>@e.idEquipe</td>
                <td>@e.Nome</td>
                <td>@e.Imagem</td>
            </tr>
        }
    </tbody>
</table>

Backend e serviços na nuvem da Microsoft Azure/aula04/EJOGOS/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Atualização do GIT PARA O AZURE!!!!</h1> 
	<a class="navbar-brand" asp-area="" asp-controller="Equipe" asp-action="Index">Equipes</a>
</div>

Backend e serviços na nuvem da Microsoft Azure/aula04/EJOGOS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EJOGOS</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EJOGOS</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - EJOGOS - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>